services:
  ordering-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ordering-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    volumes:
      - ordering-db-data:/var/opt/mssql

  ordering-rabbitmq:
    image: rabbitmq:3-management
    container_name: ordering-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"     # AMQP (uygulamalar buraya bağlanır)
      - "15672:15672"   # Yönetim arayüzü (tarayıcı): http://localhost:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ordering-api:
    build:
      context: .
      dockerfile: src/Ordering.Api/Dockerfile
    container_name: ordering-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__OrderingDb: "Server=ordering-db,1433;Database=Ecommerce_OrderingDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True"
      RabbitMq__Host: "ordering-rabbitmq"
      Identity__Issuer: "http://host.docker.internal:5001/"
    ports:
      - "5004:8080"
    depends_on:
      ordering-rabbitmq:
        condition: service_healthy

volumes:
  ordering-db-data:
